name: Test Go-Rest API

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: flake8 Lint
        run: flake8 --max-line-length=120
      - name: Copy secret API bearer token
        env:
          GO_REST_TEST_KEY: ${{ secrets.GO_REST_TEST_KEY }}
        run:
          echo GO_REST_TEST_KEY=$GO_REST_TEST_KEY > .env
      - name: Test with pytest
        run: pytest -v